# Config file for CelebA dataset (200k)

output_dir: '/content/output/celeba'
structure: 'linear'
device_id: ('0')
use_ema: False
checkpoint_factor: 0
feedback_factor: 2
dataset:
  img_dir: '/content/drive/MyDrive/datasets/celeba/'
  folder: False
  resolution: 64
  channels: 3
sched:
  epochs: [8,8,8,8,64,64]
  batch_sizes: [128, 128, 128, 64, 32, 16, 8, 4, 2]
  simp_start_end: [0.0005,0.0005] 
  vae_probs: '[(1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (1,1)]'
  dis_probs: '[(0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0)]'
  gen_probs: '[(0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0)]'
  sleep_probs: '[(0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0)]'
