# Config file for CelebA dataset (200k)

output_dir: '/content/output/ffhq'
structure: 'linear'
device_id: ('0')
use_ema: False
checkpoint_factor: 0
feedback_factor: 2
dataset:
  img_dir: '/content/drive/MyDrive/datasets/ffhq'
  folder: True
  resolution: 128
sched:
  epochs: [32,32,32,16,16,64]
  simp_start_end: [0.0005,0.0005] 
  vae_probs: '[(1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (0,0), (0,0), (0,1)]'
  dis_probs: '[(1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (0,0), (0,0), (0,1)]'
  gen_probs: '[(1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (0,0), (0,0), (0,1)]'
  sleep_probs: '[(0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0)]'