# Config file for CelebA dataset (200k)

output_dir: '/content/output/mnist'
structure: 'linear'
device_id: ('0')
use_ema: False
checkpoint_factor: 0
feedback_factor: 2
recon_beta: 5
feature_beta: 0
use_CB: False
dataset:
  img_dir: '/content/drive/MyDrive/datasets/mnist/training'
  folder: True
  resolution: 32
  channels: 1
sched:
  epochs: [8,8,4,32,64,64]
  batch_sizes: [128, 128, 128, 64, 32, 16, 8, 4, 2]
  simp_start_end: [0,1] 
  vae_probs: '[(1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (0,0), (0,0), (0,1)]'
  dis_probs: '[(0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0)]'
  gen_probs: '[(0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0)]'
  sleep_probs: '[(0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0)]'
model:
  g_optim:
    learning_rate: 0.0004
  d_optim:
    learning_rate: 0.0004
  dis:
    encode_in: 'Z'
