output_dir: '/home/mms496/StyleVAE_Experiments/stylegan_adapt_disc/mnist/GAN-cb-g3d4'
structure: 'linear'
device_id: ('0')
checkpoint_factor: 2
feedback_factor: 1
use_CB: True
dataset:
  img_dir: '/var/scratch/mms496/data/mnist'
  folder: True
  resolution: 32
  channels: 1
sched:
  epochs: [8,8,8,300,0,0]  ### 14 uur == 11 epochs
  simp_start_end: [0.005,3.0]
  fade_in_percentage: [50, 50, 50, 5, 50, 50, 50, 50, 50]
  vae_probs: '[(0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0)]'
  sleep_probs: '[(0,0), (0,0), (0,0.5), (0.5,5), (0,0), (0,0), (0,0), (0,0), (0,0)]'
  dis_probs: '[(1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (1,1)]'
  gen_probs: '[(1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (1,1)]'
model:
  g_optim:
    learning_rate: 0.0003
  d_optim:
    learning_rate: 0.0004
