output_dir: '/home/mms496/StyleVAE_Experiments/stylegan_adapt_disc/cb-r05f05'
structure: 'linear'
device_id: ('0')
checkpoint_factor: 2
feedback_factor: 1
recon_beta: 0.5
feature_beta: 0.5
use_CB: True
dataset:
  img_dir: '/var/scratch/mms496/data/mnist'
  folder: True
  resolution: 32
  channels: 1
sched:
  epochs: [8,8,8,300,300,100]  ### 14 uur == 11 epochs
  simp_start_end: [0.001,0.001]
  fade_in_percentage: [50, 50, 50, 50, 1, 50, 50, 50, 50]
  vae_probs: '[(1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (1,1), (1,1)]'
  sleep_probs: '[(0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0)]'
  dis_probs: '[(0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0)]'
  gen_probs: '[(0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0), (0,0)]'
model:
  g_optim:
    learning_rate: 0.0004
  d_optim:
    learning_rate: 0.0004
