# Config file for CelebA dataset (200k)

output_dir: '/home/mms496/StyleVAE_Experiments/stylegan_adapt_disc/0|05-2'
structure: 'linear'
device_id: ('0')
checkpoint_factor: 0
feedback_factor: 1
dataset:
  img_dir: '/var/scratch/mms496/data/ffhq/full/thumbnails128x128'
  folder: True
  resolution: 128
sched:
  epochs: [8,8,8,3,3,30]  ### 14 uur == 11 epochs
  simp_start_end: [-1,-1]
  vae_probs: '[(0,0.1), (0.1,0.2), (0.2,0.3), (0.3,0.4), (0.4,0.5), (0.5,6), (0,0), (0,0), (0,0)]'
  dis_probs: '[(1,1), (1,1), (1,1), (1,1), (1,1), (1,0), (0,0), (0,0), (0,1)]'
  gen_probs: '[(1,1), (1,1), (1,1), (1,1), (1,1), (1,0), (0,0), (0,0), (0,1)]'