# Config file for CelebA dataset (200k)

output_dir: '/home/mms496/StyleVAE_Experiments/stylegan_adapt_disc/1|1'
structure: 'linear'
device_id: ('0')
checkpoint_factor: 0
feedback_factor: 1
dataset:
  img_dir: '/var/scratch/mms496/data/ffhq/full/thumbnails128x128'
  folder: True
  resolution: 128
sched:
  epochs: [8,8,8,3,3,30]  ### 14 uur == 11 epochs
  simp_start_end: [-1,-1]
  vae_probs: '[(0,0.1), (0.1,0.3), (0.3,0.5), (0.5,0.8), (0.8,1), (1,1), (0,0), (0,0), (0,1)]'
model:
  gen:
    use_styles: False
    const_input_layer: False