# Config file for CelebA dataset (200k)

output_dir: '/content/output/ffhq'
structure: 'linear'
device_id: ('0')
use_ema: False
checkpoint_factor: 0
feedback_factor: 2
dataset:
  img_dir: '/content/drive/MyDrive/datasets/ffhq'
  folder: True
  resolution: 128
sched:
  epochs: [32,32,32,16,16,64]
  simp_start_end: [0,2]
  vae_probs: '[(0,0), (0,0), (0,0), (0,0), (0,0), (0,1), (0,0), (0,0), (0,0)]'
  dis_probs: '[(1,0), (1,0), (1,0), (1,0), (1,0), (1,0), (0,0), (0,0), (0,1)]'
  gen_probs: '[(1,0), (1,0), (1,0), (1,0), (1,0), (1,0), (0,0), (0,0), (0,1)]'
model:
  gen:
    use_styles: False
    const_input_layer: False