# Config file for CelebA dataset (200k)

output_dir: '/home/mms496/StyleVAE_Experiments/stylegan_adapt_disc/ffhq/'
structure: 'linear'
device_id: ('0')
checkpoint_factor: 0
feedback_factor: 1
dataset:
  img_dir: '/var/scratch/mms496/data/ffhq/full/thumbnails128x128'
  folder: True
  resolution: 128
sched:
  epochs: [1,1,1,1,1,50]
