# Config file for CelebA dataset (200k)

output_dir: '/home/mms496/StyleVAE_Experiments/stylegan_adapt_disc/OFF|05-1'
structure: 'linear'
device_id: ('0')
checkpoint_factor: 0
feedback_factor: 1
dataset:
  img_dir: '/var/scratch/mms496/data/ffhq/full/thumbnails128x128'
  folder: True
  resolution: 128
sched:  
  epochs: [8,8,8,4,3,10]  ### 14 uur == 11 epochs
  simp_start_end: [-1,-1]
  vae_probs: '[(0,0.1), (0.1,0.2), (0.2,0.3), (0.3,0.4), (0.4,0.5), (0.5,1), (0,0), (0,0), (0,0)]'
model:
  gen:
    blur_filter: None
use_ema: False
