# Config file for CelebA dataset (200k)

output_dir: '/home/mms496/StyleVAE_Experiments/stylegan_adapt_disc/ON|05-1-R'
structure: 'linear'
device_id: ('0')
checkpoint_factor: 0
feedback_factor: 1
dataset:
  img_dir: '/var/scratch/mms496/data/ffhq/full/thumbnails128x128'
  folder: True
  resolution: 128
sched:
  epochs: [8,8,8,3,3,10]  ### 14 uur == 11 epochs
  simp_start_end: [-1,-1]
  vae_probs: '[(0,0.1), (0,0.2), (0,0.3), (0,0.4), (0,0.5), (0.5,4), (0,0), (0,0), (0,1)]'
