# Config file for CelebA dataset (200k)

output_dir: '/home/mms496/StyleVAE_Experiments/stylegan_original/gan'
structure: 'linear'
device_id: ('0')
checkpoint_factor: 0
feedback_factor: 2
dataset:
  img_dir: '/var/scratch/mms496/data/ffhq/full/thumbnails128x128'
  folder: True
  resolution: 128
sched:
  epochs: [8,16,32,32,64,64]
